### ISSUE TITLE
出现 Uncaught Error: Class 'Gouguoyin\EasyHttp\Http' not found 无法加载类的情况

### ISSUE THREAD

**Issue by muxik** [gouguoyin/easyhttp#1]
__具体出错代码__
```php
<?php

require 'vendor/autoload.php';

use Gouguoyin\EasyHttp\Http;

$response = Http::get('http://httpbin.org/get');

```

__报错信息__

```bash
PHP Fatal error:  Uncaught Error: Class 'Gouguoyin\EasyHttp\Http' not found in /srv/http/Reqt/main.php:7
Stack trace:
#0 {main}
  thrown in /srv/http/Reqt/main.php on line 7

Process finished with exit code 255

```

**Comment by muxik** [comment]
希望尽快修复

**Comment by gouguoyin** [comment]
你是用composer安装的吗？看下你的vendor目录下是否有gouguoyin/easyhttp目录



---原始邮件---
发件人: "muxik"<notifications@github.com&gt;
发送时间: 2020年3月29日(周日) 凌晨1:39
收件人: "gouguoyin/easyhttp"<easyhttp@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [gouguoyin/easyhttp] 出现 Uncaught Error: Class 'Gouguoyin\EasyHttp\Http' not found 无法加载类的情况 (#1)




 
具体出错代码
 <?php  require 'vendor/autoload.php';  use Gouguoyin\EasyHttp\Http;  $response = Http::get('http://httpbin.org/get'); 
 
报错信息
 PHP Fatal error:  Uncaught Error: Class 'Gouguoyin\EasyHttp\Http' not found in /srv/http/Reqt/main.php:7 Stack trace: #0 {main}   thrown in /srv/http/Reqt/main.php on line 7 Process finished with exit code 255

**Comment by muxik** [comment]
**我是用composer安装的**

**目录结构如下**

```
.
├── composer.json
├── composer.lock
├── main.php
└── vendor
    ├── autoload.php
    ├── composer
    │   ├── autoload_classmap.php
    │   ├── autoload_files.php
    │   ├── autoload_namespaces.php
    │   ├── autoload_psr4.php
    │   ├── autoload_real.php
    │   ├── autoload_static.php
    │   ├── ClassLoader.php
    │   ├── installed.json
    │   └── LICENSE
    ├── gouguoyin
    │   └── easyhttp
    │       ├── composer.json
    │       ├── LICENSE
    │       ├── README.md
    │       └── src
    │           ├── ConnectionException.php
    │           ├── Facade.php
    │           ├── Http.php
    │           ├── RequestException.php
    │           ├── Request.php
    │           └── Response.php
    ├── guzzlehttp
    │   ├── guzzle
    │   │   ├── CHANGELOG.md
    │   │   ├── composer.json
    │   │   ├── Dockerfile
    │   │   ├── LICENSE
    │   │   ├── README.md
    │   │   ├── src
    │   │   │   ├── ClientInterface.php
    │   │   │   ├── Client.php
    │   │   │   ├── Cookie
    │   │   │   │   ├── CookieJarInterface.php
    │   │   │   │   ├── CookieJar.php
    │   │   │   │   ├── FileCookieJar.php
    │   │   │   │   ├── SessionCookieJar.php
    │   │   │   │   └── SetCookie.php
    │   │   │   ├── Exception
    │   │   │   │   ├── BadResponseException.php
    │   │   │   │   ├── ClientException.php
    │   │   │   │   ├── ConnectException.php
    │   │   │   │   ├── GuzzleException.php
    │   │   │   │   ├── InvalidArgumentException.php
    │   │   │   │   ├── RequestException.php
    │   │   │   │   ├── SeekException.php
    │   │   │   │   ├── ServerException.php
    │   │   │   │   ├── TooManyRedirectsException.php
    │   │   │   │   └── TransferException.php
    │   │   │   ├── functions_include.php
    │   │   │   ├── functions.php
    │   │   │   ├── Handler
    │   │   │   │   ├── CurlFactoryInterface.php
    │   │   │   │   ├── CurlFactory.php
    │   │   │   │   ├── CurlHandler.php
    │   │   │   │   ├── CurlMultiHandler.php
    │   │   │   │   ├── EasyHandle.php
    │   │   │   │   ├── MockHandler.php
    │   │   │   │   ├── Proxy.php
    │   │   │   │   └── StreamHandler.php
    │   │   │   ├── HandlerStack.php
    │   │   │   ├── MessageFormatter.php
    │   │   │   ├── Middleware.php
    │   │   │   ├── Pool.php
    │   │   │   ├── PrepareBodyMiddleware.php
    │   │   │   ├── RedirectMiddleware.php
    │   │   │   ├── RequestOptions.php
    │   │   │   ├── RetryMiddleware.php
    │   │   │   ├── TransferStats.php
    │   │   │   └── UriTemplate.php
    │   │   └── UPGRADING.md
    │   ├── promises
    │   │   ├── CHANGELOG.md
    │   │   ├── composer.json
    │   │   ├── LICENSE
    │   │   ├── Makefile
    │   │   ├── README.md
    │   │   └── src
    │   │       ├── AggregateException.php
    │   │       ├── CancellationException.php
    │   │       ├── Coroutine.php
    │   │       ├── EachPromise.php
    │   │       ├── FulfilledPromise.php
    │   │       ├── functions_include.php
    │   │       ├── functions.php
    │   │       ├── PromiseInterface.php
    │   │       ├── Promise.php
    │   │       ├── PromisorInterface.php
    │   │       ├── RejectedPromise.php
    │   │       ├── RejectionException.php
    │   │       ├── TaskQueueInterface.php
    │   │       └── TaskQueue.php
    │   └── psr7
    │       ├── CHANGELOG.md
    │       ├── composer.json
    │       ├── LICENSE
    │       ├── README.md
    │       └── src
    │           ├── AppendStream.php
    │           ├── BufferStream.php
    │           ├── CachingStream.php
    │           ├── DroppingStream.php
    │           ├── FnStream.php
    │           ├── functions_include.php
    │           ├── functions.php
    │           ├── InflateStream.php
    │           ├── LazyOpenStream.php
    │           ├── LimitStream.php
    │           ├── MessageTrait.php
    │           ├── MultipartStream.php
    │           ├── NoSeekStream.php
    │           ├── PumpStream.php
    │           ├── Request.php
    │           ├── Response.php
    │           ├── Rfc7230.php
    │           ├── ServerRequest.php
    │           ├── StreamDecoratorTrait.php
    │           ├── Stream.php
    │           ├── StreamWrapper.php
    │           ├── UploadedFile.php
    │           ├── UriNormalizer.php
    │           ├── Uri.php
    │           └── UriResolver.php
    ├── psr
    │   └── http-message
    │       ├── CHANGELOG.md
    │       ├── composer.json
    │       ├── LICENSE
    │       ├── README.md
    │       └── src
    │           ├── MessageInterface.php
    │           ├── RequestInterface.php
    │           ├── ResponseInterface.php
    │           ├── ServerRequestInterface.php
    │           ├── StreamInterface.php
    │           ├── UploadedFileInterface.php
    │           └── UriInterface.php
    └── ralouphie
        └── getallheaders
            ├── composer.json
            ├── LICENSE
            ├── README.md
            └── src
                └── getallheaders.php

21 directories, 128 files

```

**Comment by gouguoyin** [comment]
你把完整的报错trace信息发下

**Comment by gouguoyin** [comment]
> **我是用composer安装的**
> 
> **目录结构如下**
> 
> ```
> .
> ├── composer.json
> ├── composer.lock
> ├── main.php
> └── vendor
>     ├── autoload.php
>     ├── composer
>     │   ├── autoload_classmap.php
>     │   ├── autoload_files.php
>     │   ├── autoload_namespaces.php
>     │   ├── autoload_psr4.php
>     │   ├── autoload_real.php
>     │   ├── autoload_static.php
>     │   ├── ClassLoader.php
>     │   ├── installed.json
>     │   └── LICENSE
>     ├── gouguoyin
>     │   └── easyhttp
>     │       ├── composer.json
>     │       ├── LICENSE
>     │       ├── README.md
>     │       └── src
>     │           ├── ConnectionException.php
>     │           ├── Facade.php
>     │           ├── Http.php
>     │           ├── RequestException.php
>     │           ├── Request.php
>     │           └── Response.php
>     ├── guzzlehttp
>     │   ├── guzzle
>     │   │   ├── CHANGELOG.md
>     │   │   ├── composer.json
>     │   │   ├── Dockerfile
>     │   │   ├── LICENSE
>     │   │   ├── README.md
>     │   │   ├── src
>     │   │   │   ├── ClientInterface.php
>     │   │   │   ├── Client.php
>     │   │   │   ├── Cookie
>     │   │   │   │   ├── CookieJarInterface.php
>     │   │   │   │   ├── CookieJar.php
>     │   │   │   │   ├── FileCookieJar.php
>     │   │   │   │   ├── SessionCookieJar.php
>     │   │   │   │   └── SetCookie.php
>     │   │   │   ├── Exception
>     │   │   │   │   ├── BadResponseException.php
>     │   │   │   │   ├── ClientException.php
>     │   │   │   │   ├── ConnectException.php
>     │   │   │   │   ├── GuzzleException.php
>     │   │   │   │   ├── InvalidArgumentException.php
>     │   │   │   │   ├── RequestException.php
>     │   │   │   │   ├── SeekException.php
>     │   │   │   │   ├── ServerException.php
>     │   │   │   │   ├── TooManyRedirectsException.php
>     │   │   │   │   └── TransferException.php
>     │   │   │   ├── functions_include.php
>     │   │   │   ├── functions.php
>     │   │   │   ├── Handler
>     │   │   │   │   ├── CurlFactoryInterface.php
>     │   │   │   │   ├── CurlFactory.php
>     │   │   │   │   ├── CurlHandler.php
>     │   │   │   │   ├── CurlMultiHandler.php
>     │   │   │   │   ├── EasyHandle.php
>     │   │   │   │   ├── MockHandler.php
>     │   │   │   │   ├── Proxy.php
>     │   │   │   │   └── StreamHandler.php
>     │   │   │   ├── HandlerStack.php
>     │   │   │   ├── MessageFormatter.php
>     │   │   │   ├── Middleware.php
>     │   │   │   ├── Pool.php
>     │   │   │   ├── PrepareBodyMiddleware.php
>     │   │   │   ├── RedirectMiddleware.php
>     │   │   │   ├── RequestOptions.php
>     │   │   │   ├── RetryMiddleware.php
>     │   │   │   ├── TransferStats.php
>     │   │   │   └── UriTemplate.php
>     │   │   └── UPGRADING.md
>     │   ├── promises
>     │   │   ├── CHANGELOG.md
>     │   │   ├── composer.json
>     │   │   ├── LICENSE
>     │   │   ├── Makefile
>     │   │   ├── README.md
>     │   │   └── src
>     │   │       ├── AggregateException.php
>     │   │       ├── CancellationException.php
>     │   │       ├── Coroutine.php
>     │   │       ├── EachPromise.php
>     │   │       ├── FulfilledPromise.php
>     │   │       ├── functions_include.php
>     │   │       ├── functions.php
>     │   │       ├── PromiseInterface.php
>     │   │       ├── Promise.php
>     │   │       ├── PromisorInterface.php
>     │   │       ├── RejectedPromise.php
>     │   │       ├── RejectionException.php
>     │   │       ├── TaskQueueInterface.php
>     │   │       └── TaskQueue.php
>     │   └── psr7
>     │       ├── CHANGELOG.md
>     │       ├── composer.json
>     │       ├── LICENSE
>     │       ├── README.md
>     │       └── src
>     │           ├── AppendStream.php
>     │           ├── BufferStream.php
>     │           ├── CachingStream.php
>     │           ├── DroppingStream.php
>     │           ├── FnStream.php
>     │           ├── functions_include.php
>     │           ├── functions.php
>     │           ├── InflateStream.php
>     │           ├── LazyOpenStream.php
>     │           ├── LimitStream.php
>     │           ├── MessageTrait.php
>     │           ├── MultipartStream.php
>     │           ├── NoSeekStream.php
>     │           ├── PumpStream.php
>     │           ├── Request.php
>     │           ├── Response.php
>     │           ├── Rfc7230.php
>     │           ├── ServerRequest.php
>     │           ├── StreamDecoratorTrait.php
>     │           ├── Stream.php
>     │           ├── StreamWrapper.php
>     │           ├── UploadedFile.php
>     │           ├── UriNormalizer.php
>     │           ├── Uri.php
>     │           └── UriResolver.php
>     ├── psr
>     │   └── http-message
>     │       ├── CHANGELOG.md
>     │       ├── composer.json
>     │       ├── LICENSE
>     │       ├── README.md
>     │       └── src
>     │           ├── MessageInterface.php
>     │           ├── RequestInterface.php
>     │           ├── ResponseInterface.php
>     │           ├── ServerRequestInterface.php
>     │           ├── StreamInterface.php
>     │           ├── UploadedFileInterface.php
>     │           └── UriInterface.php
>     └── ralouphie
>         └── getallheaders
>             ├── composer.json
>             ├── LICENSE
>             ├── README.md
>             └── src
>                 └── getallheaders.php
> 
> 21 directories, 128 files
> ```

你把完整的报错trace信息发下

**Comment by gouguoyin** [comment]
> **具体出错代码**
> 
> ```
> <?php
> 
> require 'vendor/autoload.php';
> 
> use Gouguoyin\EasyHttp\Http;
> 
> $response = Http::get('http://httpbin.org/get');
> ```
> 
> **报错信息**
> 
> ```shell
> PHP Fatal error:  Uncaught Error: Class 'Gouguoyin\EasyHttp\Http' not found in /srv/http/Reqt/main.php:7
> Stack trace:
> #0 {main}
>   thrown in /srv/http/Reqt/main.php on line 7
> 
> Process finished with exit code 255
> ```

你把完整的报错trace信息发下

**Comment by muxik** [comment]
```
>>> php main.php 
PHP Fatal error:  Uncaught Error: Class 'Gouguoyin\EasyHttp\Http' not found in /srv/http/Reqt/main.php:7
Stack trace:
#0 {main}
  thrown in /srv/http/Reqt/main.php on line 7

Fatal error: Uncaught Error: Class 'Gouguoyin\EasyHttp\Http' not found in /srv/http/Reqt/main.php on line 7

Error: Class 'Gouguoyin\EasyHttp\Http' not found in /srv/http/Reqt/main.php on line 7

Call Stack:
    0.0174     896160   1. {main}() /srv/http/Reqt/main.php:0
```

**Comment by gouguoyin** [comment]
你删除vendor/gouguoyin目录，运行composer update重新安装。

**Comment by muxik** [comment]
问题解决了,感谢作者!
